//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotasAcademicasNegocio.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleEstudiantes
    {
        public int IdDetalleEstudiantes { get; set; }
        public Nullable<int> Id_Fr_Matricula_E { get; set; }
        public Nullable<int> Id_Fr_Estudiantes_E { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
        public virtual Matricula Matricula { get; set; }
    }
}
