//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotasAcademicasNegocio.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materia()
        {
            this.DetalleNotas = new HashSet<DetalleNotas>();
        }
    
        public int IdMateria { get; set; }
        public string Dependencia { get; set; }
        public string Modalidad { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string Prerrequisito { get; set; }
        public Nullable<int> Nivel { get; set; }
        public Nullable<int> NumeroCredito { get; set; }
    
        public virtual DetalleMatricula DetalleMatricula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleNotas> DetalleNotas { get; set; }
    }
}
